version: 2

sources:
  - name: gold
    database: rba-pipeline-494410
    schema: gold
    tables:
      - name: stg_interest_rates_raw
        columns:
          - name: date
            tests: 
              - not_null
          - name: indicator_id
            tests: 
              - not_null
          - name: countryiso3code
            tests:
              - not_null
      - name: ext_cpi
        columns:
          - name: date
            tests:
            - not_null
          - name: trimmed_mean_yoy
            tests:
            - not_null
          - name: trimmed_mean_quarterly
            tests:
            - not_null
      - name: ext_labour_force
        columns:
          - name: date
            tests: 
            - not_null
          - name: unemployed__
            tests: 
            - not_null
          - name: unemployed_trend
            tests: 
            - not_null
      - name: ext_commodity_prices
        columns:
          - name: date
            tests: 
            - not_null
          - name: overall_AU_
            tests: 
            - not_null
          - name: bulk_AU_
            tests: 
            - not_null
      - name: ext_government_expenditure
        columns:
          - name: date
            tests: 
            - not_null
          - name: household_consump
            tests: 
            - not_null
          - name: government_spending
            tests: 
            - not_null
      - name: ext_gdp
        columns:
          - name: date
            tests: 
            - not_null
          - name: GDP__
            tests: 
            - not_null
          - name: ratio_exp_to_imp
            tests: 
            - not_null
      - name: ext_productivity
        columns:
          - name: date
            tests: 
            - not_null
          - name: year_ended_wage_growth
            tests: 
            - not_null
          - name: year_ended_productivity_growth
            tests: 
            - not_null
      - name: rba_decisions
        columns:
          - name: date
            tests:
            - not_null
          - name: cash_rate
            tests:
            - not_null

  - name: rba_minutes
    database: finance-lakehouse
    schema: rba_minutes
    tables:
      - name: sentiment
        columns:
          - name: date
            tests:
            - not_null
          - name: sentiment
            tests:
            - not_null
          - name: confidence
            tests:
            - not_null
          - name: dominant_concern
            tests:
            - not_null

models:
  - name: stg_cpi
    columns:
      - name: date
        tests: [not_null, unique]
      - name: trimmed_mean_yoy
        tests:
          - dbt_utils.accepted_range:
              arguments: 
                min_value: -5
                max_value: 20

  - name: stg_labour_force
    columns:
      - name: date
        tests: [not_null, unique]
      - name: unemployed__
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 20

  - name: stg_commodity_prices
    columns:
      - name: date
        tests: [not_null, unique]
      - name: overall_AU_
        tests:
          - dbt_utils.accepted_range:
              arguments: 
                min_value: 0
                max_value: 1000

  - name: stg_government_expenditure
    columns:
      - name: date
        tests: [not_null, unique]
      - name: government_spending
        tests:
          - dbt_utils.accepted_range:
              arguments: 
                min_value: -20
                max_value: 20

  - name: stg_gdp
    columns:
      - name: date
        tests: [not_null, unique]
      - name: GDP__
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: -20
                max_value: 20

  - name: stg_productivity
    columns:
      - name: date
        tests: [not_null, unique]
      - name: year_ended_productivity_growth
        tests:
          - dbt_utils.accepted_range:
              arguments: 
                min_value: -20
                max_value: 20

  - name: stg_rba_decisions
    columns:
      - name: date
        tests: [not_null, unique]
      - name: cash_rate
        tests: 
          - dbt_utils.accepted_range:
              arguments: 
                min_value: 0
                max_value: 20

  # Grain is the pair, not the date: 66 years x 6 indicators. A plain unique
  # test on date would fail on correct data.
  - name: stg_interest_rates
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [date, indicator_id]

  - name: stg_sentiment
    columns:
      - name: decision_date
        tests: [not_null, unique]

      - name: sentiment
        tests: 
          - accepted_values:
              arguments:
                values: ['dovish', 'neutral', 'hawkish']
      - name: confidence
        tests:
          - dbt_utils.accepted_range:
              arguments: 
                min_value: 1
                max_value: 5

      - name: dominant_concern
        tests: 
          - accepted_values:
              arguments:
                values: ['balanced', 'growth', 'inflation']

